version: '3.3'

services:
   db:
     build: 
       context: ./
       dockerfile: ./bin/docker/mysql/Dockerfile
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     ports:
      - "9906:3306"
     stdin_open: true
     tty: true

   wordpress:
     depends_on:
       - db
     build: 
      context: ./
      dockerfile: ./bin/docker/wordpress/Dockerfile
     volumes: 
       - ./src/theme:/var/www/html/wp-content/themes/ynotradio
       - ./src/plugins:/var/www/html/wp-content/plugins
       - ./src/vendor:/var/www/html/vendor
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DEBUG: 1
         
volumes:
    db_data: